# trunk-ignore-all(semgrep/yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha)
name: MergeTest
run-name: Tests for PRs in Merge for ${{ github.ref_name }}

on:
  push:
    branches:
      - trunk-merge/**

jobs:
  pr:
    name: Run Pull Request checks
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build
        run: sleep 5s

      - name: Check for fail file existence
        id: run_forever
        uses: andstor/file-existence-action@v1
        with:
          files: "**/fail_tests*.txt"

      - name: Run forever
        if:
          steps.run_forever.outputs.files_exists == 'true' && startsWith(env.BRANCH_NAME,
          'trunk-merge')
        run: sleep 180s
